# Author: https://github.com/RastalDev
# This is a Dracula theme for tut, a Mastodon TUI
# Put draculatut.toml in ~/.config/tut/themes
# Set theme="draculatut" in config.toml
background="#282a36"
text="#f8f8f2"
subtle="#44475A"
warning-text="#ff5555"
text-special-one="#bd93f9"
text-special-two="#50fa7b"
top-bar-background="#282a36"
top-bar-text="#f8f8f2"
status-bar-background="#282a36"
status-bar-text="#f8f8f2"
status-bar-view-background="#bd93f9"
status-bar-view-text="#f8f8f2"
list-selected-background="#44475A"
list-selected-text="#f8f8f2"
list-selected-inactive-background="#282a36"
list-selected-inactive-text="#f8f8f2"
controls-text="#f8f8f2"
controls-highlight="#50fa7b"
autocomplete-background="#bd93f9"
autocomplete-text="#f8f8f2"
autocomplete-selected-background="#ae81ff"
autocomplete-selected-text="#f8f8f2"
button-color-one="#ff5555"
button-color-two="#bd93f9"
timeline-name-background="#bd93f9"
timeline-name-text="#44475A"
command-text="#f8f8f2"
